<?php
/**
 * @var $this PageFormDecorator
 */

use Cubex\Quantum\Modules\Pages\Controllers\Admin\Forms\PageForm;
use Cubex\Quantum\Modules\Pages\Controllers\Admin\Forms\PageFormDecorator;
use PackagedUi\Fusion\Button\Button;

/** @var PageForm $form */
$form = $this->getForm();
?>
<style>
  .page-attributes {
    display: flex;
  }

  .page-attributes .p-form-field {
    flex-basis: 50%;
  }

  .page-attributes .p-form-field .p-form--input input {
    width: 100%;
  }
</style>
<div class="page-attributes">
  <?= $form->title->render(); ?>
  <?= $form->path->render(); ?>
</div>
<?= $form->content->render(); ?>
<div style="display: flex; padding: 10px 0;">
  <?= Button::create('Save') ?> &nbsp;
  <?= Button::create('Save & Publish')->setAttribute('name', '_publish') ?>
</div>

<div style="display: none;">
  <?= $form->id->render(); ?>
  <?= $form->version->render(); ?>
</div>

