<?php
/**
 * @var $this NoTheme
 */

use Cubex\Quantum\Themes\NoTheme\NoTheme;
use Packaged\Dispatch\Dispatch;
use Packaged\Dispatch\ResourceStore;

?>
<!DOCTYPE html>
<html>
<head lang="en">
  <meta charset="UTF-8">
  <?= Dispatch::instance()->store()->generateHtmlIncludes(ResourceStore::TYPE_CSS); ?>
  <title><?= $this->getPageTitle() ?></title>
</head>
<body>
<?= $this->getContent() ?>
<?= Dispatch::instance()->store()->generateHtmlIncludes(ResourceStore::TYPE_JS); ?>
</body>
</html>
