<?php
/**
 * @var $this AdminTheme
 */

use Cubex\Quantum\Themes\Admin\AdminTheme;
use Packaged\Dispatch\Dispatch as Dispatch;
use Packaged\Dispatch\ResourceStore as ResourceStore;

?>
<!DOCTYPE html>
<html>
<head>
  <meta name="viewport" content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0">
  <meta name="robots" content="noindex"/>
  <?= Dispatch::instance()->store()->generateHtmlIncludes(ResourceStore::TYPE_CSS); ?>
  <title><?= $this->getPageTitle() ?></title>
</head>
<body>
<?= $this->getHeader(); ?>
<?= $this->getContent(true); ?>
<?php echo Dispatch::instance()->store()->generateHtmlIncludes(ResourceStore::TYPE_JS); ?>
</body>
</html>
